### ISSUE TITLE
Nella versione 0.3 usando ENTER appare due volte il messaggio di alert.

### ISSUE THREAD

**Issue by Roccaus** [arialdomartini/IndoorRoccaus#18]
Please fix ;-)

**Comment by arialdomartini** [comment]
Io non riesco a riprodurre questo bug...

**Comment by Roccaus** [comment]
Ho appena riprovato. Con Safari 8.0.8 e Mac OS X 10.10.5 è riproducibile e ho scoperto che il giocatore viene registrato due volte! Per quello escono anche due messaggi.

**Comment by lucax88x** [comment]
si riproduce anche con chrome, ora vedo perchè!
