### ISSUE TITLE
Ora di registrazione sbagliata

### ISSUE THREAD

**Issue by Roccaus** [arialdomartini/IndoorRoccaus#20]
L'ora di ogni registrazione è in ritardo di due ore. Bisogna correggere il fuso orario.

**Comment by arialdomartini** [comment]
@Roccaus `service.php` salva l'ora in UTC ([il fuso orario di riferimento](https://it.wikipedia.org/wiki/Tempo_coordinato_universale), indipendente da ore legali e fusi orari). Di solito è una buona pratica far sì che il backend sia indipendente dal fuso orario di chi sta usando l'applicazione (il tuo amico Pluto potrebbe volersi iscrivere al torneo da San Francisco, dove è andato in vacanza, e tu stesso potresti desiderare di spostare il sito da un server in Ticino ad uno a New York, su cloud Amazon: il codice è resiliente a questi dettagli).

Ovvio che poi al momento della visualizzazione ti interessa avere un fuso orario preferito (nello specifico, UTC/GMT, che fa +1 ora per il fuso e +1 ora per l'ora legale, da cui le 2 ore di differenza che tu giustamente segnali nella issue). Dovrebbe pensarci, di solito, il frontend.

@lucax88x, se sei d'accordo che sia una cosa da fare lato JS, hai modo modificare il codice in modo da visualizzare l'ora nel fuso orario corretto?

**Comment by lucax88x** [comment]
@arialdomartini  d'accordissimo, ora procedo

**Comment by Roccaus** [comment]
Grande!!
Siete riusciti a ricostruire il bug #18?

**Comment by Roccaus** [comment]
Grazie Luca. Ora manca soltanto un bug! Il numero #18 con Safari.
